# Generated by Django 6.0.2 on 2026-03-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='integration',
            name='tool_name',
            field=models.CharField(max_length=50),
        ),
    ]
